"""
Internal Support App - Day 1 homework (+ bonus features).

A minimal Flask app backed by Lakebase (Databricks-managed Postgres). It lets a
user view support tickets, read a ticket's messages, create tickets, add
messages, change a ticket's status and priority, filter tickets by status, and
delete a ticket via a confirmation step. All data is read from and written to
Lakebase via the connection helper in lakebase.py.

Deployment: Databricks Apps runs this with `python app.py` (see app.yaml) and
injects the port via DATABRICKS_APP_PORT. The app also listens on 8000 by
default, which is the Databricks Apps default.
"""

import os

from flask import (
    Flask,
    abort,
    flash,
    redirect,
    render_template,
    request,
    url_for,
)

# get_connection is reused for INSERT ... RETURNING (needs the returned id AND a
# commit); run_query / run_write cover the read and non-returning write paths.
from lakebase import get_connection, run_query, run_write

app = Flask(__name__)
app.secret_key = os.environ.get("FLASK_SECRET_KEY", "change-me-in-app-yaml")

# The status values the UI and CHECK constraint both agree on.
VALID_STATUSES = ("open", "in_progress", "resolved")
STATUS_LABELS = {
    "open": "Open",
    "in_progress": "In progress",
    "resolved": "Resolved",
}

# Priority values, ordered low -> high (the CHECK constraint enforces the same).
VALID_PRIORITIES = ("low", "medium", "high")
PRIORITY_LABELS = {"low": "Low", "medium": "Medium", "high": "High"}

# Kept in sync with schema.sql. CREATE TABLE IF NOT EXISTS handles fresh installs;
# the ADD COLUMN / ADD CONSTRAINT guards upgrade a table created by an earlier
# version of this app that did not yet have the priority column.
_DDL = """
CREATE TABLE IF NOT EXISTS tickets (
    ticket_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       TEXT        NOT NULL,
    status      TEXT        NOT NULL DEFAULT 'open'
                            CONSTRAINT tickets_status_check
                            CHECK (status IN ('open', 'in_progress', 'resolved')),
    priority    TEXT        NOT NULL DEFAULT 'medium'
                            CONSTRAINT tickets_priority_check
                            CHECK (priority IN ('low', 'medium', 'high')),
    created_by  TEXT        NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS ticket_messages (
    message_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id     BIGINT      NOT NULL
                              REFERENCES tickets (ticket_id) ON DELETE CASCADE,
    message_text  TEXT        NOT NULL,
    author        TEXT        NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_ticket_messages_ticket_id
    ON ticket_messages (ticket_id);
"""


def ensure_schema() -> None:
    """Create the tables if they don't exist yet (idempotent).

    Only issues CREATE TABLE IF NOT EXISTS, which is a no-op when the tables
    already exist. It deliberately does NOT run ALTER TABLE, because the app's
    database role may not own tables that were created by another role in the
    SQL editor, and altering them would raise "must be owner of table". Run
    schema.sql once (as an owner role) to create the schema and sample data.
    """
    try:
        run_write(_DDL)
    except Exception as exc:  # noqa: BLE001 - startup should not hard-crash here
        # If the role lacks privileges to create tables (they likely already
        # exist), log and continue so the app can still serve existing data.
        app.logger.warning("ensure_schema skipped: %s", exc)


def insert_returning(sql: str, params: tuple) -> dict:
    """Run an INSERT ... RETURNING and commit, returning the produced row."""
    with get_connection() as conn:
        with conn.cursor() as cur:
            cur.execute(sql, params)
            row = cur.fetchone()
        conn.commit()
    return row


# ---------------------------------------------------------------------------
# Data access
# ---------------------------------------------------------------------------

def list_tickets(status_filter: str | None = None) -> list[dict]:
    where = ""
    params: tuple = ()
    if status_filter in VALID_STATUSES:
        where = "WHERE t.status = %s"
        params = (status_filter,)
    sql = f"""
        SELECT t.ticket_id,
               t.title,
               t.status,
               t.priority,
               t.created_by,
               t.created_at,
               COUNT(m.message_id) AS message_count
        FROM tickets t
        LEFT JOIN ticket_messages m ON m.ticket_id = t.ticket_id
        {where}
        GROUP BY t.ticket_id, t.title, t.status, t.priority, t.created_by, t.created_at
        ORDER BY t.created_at DESC, t.ticket_id DESC
    """
    return run_query(sql, params)


def status_counts() -> tuple[dict, int]:
    rows = run_query("SELECT status, COUNT(*) AS n FROM tickets GROUP BY status")
    counts = {s: 0 for s in VALID_STATUSES}
    for r in rows:
        if r["status"] in counts:
            counts[r["status"]] = r["n"]
    return counts, sum(counts.values())


def get_ticket(ticket_id: int) -> dict | None:
    rows = run_query("SELECT * FROM tickets WHERE ticket_id = %s", (ticket_id,))
    return rows[0] if rows else None


def get_messages(ticket_id: int) -> list[dict]:
    return run_query(
        """
        SELECT message_id, ticket_id, message_text, author, created_at
        FROM ticket_messages
        WHERE ticket_id = %s
        ORDER BY created_at ASC, message_id ASC
        """,
        (ticket_id,),
    )


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------

@app.get("/healthz")
def healthz():
    """Health check for Databricks Apps."""
    return {"status": "ok"}, 200


@app.get("/")
def index():
    # Filter by status if a valid one is supplied; otherwise show everything.
    status_filter = request.args.get("status")
    if status_filter not in VALID_STATUSES:
        status_filter = None
    tickets = list_tickets(status_filter)
    counts, total = status_counts()
    return render_template(
        "index.html",
        tickets=tickets,
        status_labels=STATUS_LABELS,
        priority_labels=PRIORITY_LABELS,
        valid_priorities=VALID_PRIORITIES,
        counts=counts,
        total=total,
        active_status=status_filter,
    )


@app.post("/tickets")
def create_ticket():
    title = (request.form.get("title") or "").strip()
    created_by = (request.form.get("created_by") or "").strip()
    priority = (request.form.get("priority") or "medium").strip()
    if priority not in VALID_PRIORITIES:
        priority = "medium"

    if not title or not created_by:
        flash("A title and your name are both required to open a ticket.", "error")
        return redirect(url_for("index"))

    row = insert_returning(
        """
        INSERT INTO tickets (title, status, priority, created_by)
        VALUES (%s, 'open', %s, %s)
        RETURNING ticket_id
        """,
        (title, priority, created_by),
    )
    flash("Ticket created.", "success")
    return redirect(url_for("view_ticket", ticket_id=row["ticket_id"]))


@app.get("/tickets/<int:ticket_id>")
def view_ticket(ticket_id: int):
    ticket = get_ticket(ticket_id)
    if ticket is None:
        abort(404)
    messages = get_messages(ticket_id)
    return render_template(
        "ticket.html",
        ticket=ticket,
        messages=messages,
        valid_statuses=VALID_STATUSES,
        status_labels=STATUS_LABELS,
        valid_priorities=VALID_PRIORITIES,
        priority_labels=PRIORITY_LABELS,
    )


@app.post("/tickets/<int:ticket_id>/messages")
def add_message(ticket_id: int):
    if get_ticket(ticket_id) is None:
        abort(404)

    author = (request.form.get("author") or "").strip()
    message_text = (request.form.get("message_text") or "").strip()

    if not author or not message_text:
        flash("A name and a message are both required.", "error")
        return redirect(url_for("view_ticket", ticket_id=ticket_id))

    run_write(
        """
        INSERT INTO ticket_messages (ticket_id, author, message_text)
        VALUES (%s, %s, %s)
        """,
        (ticket_id, author, message_text),
    )
    flash("Message added.", "success")
    return redirect(url_for("view_ticket", ticket_id=ticket_id))


@app.post("/tickets/<int:ticket_id>/status")
def update_status(ticket_id: int):
    if get_ticket(ticket_id) is None:
        abort(404)

    new_status = (request.form.get("status") or "").strip()
    if new_status not in VALID_STATUSES:
        flash("That status is not allowed.", "error")
        return redirect(url_for("view_ticket", ticket_id=ticket_id))

    run_write(
        "UPDATE tickets SET status = %s WHERE ticket_id = %s",
        (new_status, ticket_id),
    )
    flash(f"Status updated to {STATUS_LABELS[new_status]}.", "success")
    return redirect(url_for("view_ticket", ticket_id=ticket_id))


@app.post("/tickets/<int:ticket_id>/priority")
def update_priority(ticket_id: int):
    if get_ticket(ticket_id) is None:
        abort(404)

    new_priority = (request.form.get("priority") or "").strip()
    if new_priority not in VALID_PRIORITIES:
        flash("That priority is not allowed.", "error")
        return redirect(url_for("view_ticket", ticket_id=ticket_id))

    run_write(
        "UPDATE tickets SET priority = %s WHERE ticket_id = %s",
        (new_priority, ticket_id),
    )
    flash(f"Priority set to {PRIORITY_LABELS[new_priority]}.", "success")
    return redirect(url_for("view_ticket", ticket_id=ticket_id))


@app.get("/tickets/<int:ticket_id>/delete")
def confirm_delete(ticket_id: int):
    ticket = get_ticket(ticket_id)
    if ticket is None:
        abort(404)
    message_count = len(get_messages(ticket_id))
    return render_template(
        "delete.html", ticket=ticket, message_count=message_count
    )


@app.post("/tickets/<int:ticket_id>/delete")
def delete_ticket(ticket_id: int):
    if get_ticket(ticket_id) is None:
        abort(404)
    # ticket_messages rows are removed automatically via ON DELETE CASCADE.
    run_write("DELETE FROM tickets WHERE ticket_id = %s", (ticket_id,))
    flash("Ticket deleted.", "success")
    return redirect(url_for("index"))


if __name__ == "__main__":
    # Create/upgrade tables on startup so a fresh instance works immediately.
    ensure_schema()
    # Databricks Apps substitutes DATABRICKS_APP_PORT into the run command; we
    # also read it here and fall back to 8000 (the Databricks Apps default).
    port = int(os.environ.get("DATABRICKS_APP_PORT", os.environ.get("PORT", "8000")))
    app.run(host="0.0.0.0", port=port)
