-- ============================================================================
-- Lakebase schema for the internal support app (Day 1 homework)
-- Target database: databricks_postgres  (default Lakebase database)
--
-- Run this ONCE against your Lakebase instance, either from:
--   - the Databricks SQL editor connected to your Lakebase instance, or
--   - a psql session using your LAKEBASE_URL.
--
-- The app (app.py) also creates/upgrades these tables on startup, so the tables
-- exist automatically on first deploy. This file remains the single source of
-- truth for the required sample data.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 1. Tables
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS tickets (
    ticket_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       TEXT        NOT NULL,
    status      TEXT        NOT NULL DEFAULT 'open'
                            CONSTRAINT tickets_status_check
                            CHECK (status IN ('open', 'in_progress', 'resolved')),
    priority    TEXT        NOT NULL DEFAULT 'medium'
                            CONSTRAINT tickets_priority_check
                            CHECK (priority IN ('low', 'medium', 'high')),
    created_by  TEXT        NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ticket_messages (
    message_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id     BIGINT      NOT NULL
                              REFERENCES tickets (ticket_id) ON DELETE CASCADE,
    message_text  TEXT        NOT NULL,
    author        TEXT        NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Helpful index for the "messages for a ticket" read path.
CREATE INDEX IF NOT EXISTS idx_ticket_messages_ticket_id
    ON ticket_messages (ticket_id);

-- ---------------------------------------------------------------------------
-- 2. Sample data (only inserted if the tickets table is currently empty,
--    so this file is safe to run more than once)
-- ---------------------------------------------------------------------------

DO $$
DECLARE
    t1 BIGINT;
    t2 BIGINT;
    t3 BIGINT;
BEGIN
    IF (SELECT COUNT(*) FROM tickets) = 0 THEN

        INSERT INTO tickets (title, status, priority, created_by)
        VALUES ('Cannot log in to the analytics dashboard', 'open', 'high', 'priya.rao')
        RETURNING ticket_id INTO t1;

        INSERT INTO tickets (title, status, priority, created_by)
        VALUES ('Export to CSV is missing the last column', 'in_progress', 'medium', 'daniel.kim')
        RETURNING ticket_id INTO t2;

        INSERT INTO tickets (title, status, priority, created_by)
        VALUES ('Request: add dark mode to the reporting UI', 'resolved', 'low', 'sara.ahmed')
        RETURNING ticket_id INTO t3;

        INSERT INTO ticket_messages (ticket_id, author, message_text) VALUES
            (t1, 'priya.rao',   'I get an "invalid credentials" error even after resetting my password.'),
            (t1, 'support.bot', 'Thanks Priya — can you confirm which browser you are using?'),

            (t2, 'daniel.kim',  'The CSV export drops the "region" column that shows in the table.'),
            (t2, 'j.torres',    'Reproduced on my side. Looks like a header-mapping bug in the export job.'),
            (t2, 'j.torres',    'Fix is in review; will update once it ships to staging.'),

            (t3, 'sara.ahmed',  'Would love a dark theme for late-night reporting sessions.'),
            (t3, 'm.oconnor',   'Shipped in release 4.8 — closing this out. Thanks for the suggestion!');

    END IF;
END $$;
